export interface SeedListing {
  id: string;
  ownerUserId: string;
  categoryKey: string;
  slug: string;
  status: "ACTIVE" | "DRAFT" | "COMPLETED";
  title: string;
  summary: string;
  scope: string;
  answersJson: Record<string, unknown>;
  tags: string[];
  budgetMode: "FIXED_RANGE" | "HOURLY_RATE" | "OPEN_BID";
  budgetCurrency: string;
  budgetMin: string;
  budgetMax: string;
  timelineMode: "DURATION_ESTIMATE" | "TARGET_DATE";
  timelineValue: number;
  timelineUnit: string;
  viewCount: number;
  clickCount: number;
  matchedAt?: Date;
  completedAt?: Date;
}

export const SEED_LISTINGS: SeedListing[] = [
  {
    id: "e0000000-0000-0000-0000-000000000001",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "frontend-ui",
    slug: "nextjs-ve-tailwind-ile-modern-e-ticaret-arayuzu-gelistirilmesi-a1b2c3",
    status: "ACTIVE",
    title: "Next.js ve Tailwind ile Modern E-Ticaret Arayüzü Geliştirilmesi",
    summary:
      "Yüksek performanslı, duyarlı ve modern Next.js App Router mimarisinde e-ticaret kullanıcı arayüzü bileşenleri geliştirilecek.",
    scope:
      "Proje kapsamında Next.js 15 App Router, Tailwind CSS ve TypeScript kullanılarak modern bir e-ticaret ön yüzü geliştirilecektir. Sepet yönetimi, ürün filtreleme, arama ve ödeme adımları tasarıma birebir uygun ve erişilebilir (a11y) standartlarda kodlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: true },
    tags: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "25000",
    budgetMax: "40000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 142,
    clickCount: 89,
  },
  {
    id: "e0000000-0000-0000-0000-000000000002",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "mobile-development",
    slug: "flutter-ile-cross-platform-mobil-uygulama-gelistirilmesi-d4e5f6",
    status: "ACTIVE",
    title: "Flutter ile Cross-Platform Mobil Uygulama Geliştirilmesi",
    summary:
      "iOS ve Android platformlarında eşzamanlı çalışacak, offline-first mimaride ve modern arayüze sahip mobil proje geliştirilecek.",
    scope:
      "Projede Flutter & Dart kullanılarak yüksek performanslı bir mobil deneyim hedeflenmektedir. RESTful API entegrasyonu, push notification ve biyometrik giriş özellikleri kodlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: true },
    tags: ["Flutter", "Dart", "iOS", "Android", "REST API"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "35000",
    budgetMax: "60000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 98,
    clickCount: 64,
  },
  {
    id: "e0000000-0000-0000-0000-000000000003",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "backend-api",
    slug: "yuksek-trafikli-fintech-projesi-icin-go-ve-postgresql-api-g7h8i9",
    status: "ACTIVE",
    title: "Yüksek Trafikli Fintech Projesi için Go ve PostgreSQL API",
    summary:
      "Düşük gecikmeli, mikroservis uyumlu ve AES-256 veri korumalı dağıtık arka yüz servislerinin mimarisi ve kodlanması.",
    scope:
      "Go (Golang), Docker, PostgreSQL ve Redis kullanılarak saniyede 10.000+ istek karşılayabilecek işlem motoru geliştirilecektir. Unit ve entegrasyon testleri zorunludur.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: false },
    tags: ["Go", "Golang", "PostgreSQL", "Docker", "Redis"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "45000",
    budgetMax: "80000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 4,
    timelineUnit: "WEEKS",
    viewCount: 215,
    clickCount: 137,
  },
  {
    id: "e0000000-0000-0000-0000-000000000005",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "ai-ml",
    slug: "kurumsal-dokumanlar-icin-rag-tabanli-ai-asistan-ve-arama-motoru-j1k2l3",
    status: "ACTIVE",
    title: "Kurumsal Dokümanlar için RAG Tabanlı AI Asistan ve Arama Motoru",
    summary:
      "OpenAI / Anthropic API ve vektör veritabanı (pgvector) entegrasyonuyla şirket içi bilgi bankası asistanı geliştirilecek.",
    scope:
      "PDF, DOCX ve Notion dokümanlarını vektörize eden veri işleme pipeline'ı kurulacak. FastAPI ve LangChain / LlamaIndex mimarisiyle semantik arama ve yanıt üretimi sağlanacaktır.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: true },
    tags: ["Python", "OpenAI", "LangChain", "FastAPI", "pgvector"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "50000",
    budgetMax: "90000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 184,
    clickCount: 112,
  },
  {
    id: "e0000000-0000-0000-0000-000000000006",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "ui-ux-design",
    slug: "b2b-saas-platformu-icin-kapsamli-figma-tasarim-sistemi-m4n5o6",
    status: "ACTIVE",
    title: "B2B SaaS Platformu için Kapsamlı Figma Tasarım Sistemi ve Prototip",
    summary:
      "Tüm web ve mobil modülleri kapsayan, token tabanlı ve otomatik düzen (Auto-Layout) uyumlu Figma UI/UX tasarımı hazırlanacak.",
    scope:
      "Kullanıcı akış haritaları, wireframe'ler, tasarım tokenları (renk, tipografi, grid) ve interaktif prototipler hazırlanacaktır. Geliştirici aktarımı (developer handoff) eksiksiz teslim edilecektir.",
    answersJson: { authRequired: false, adminRequired: false, responsiveRequired: true },
    tags: ["Figma", "UI/UX", "Design System", "Prototyping", "User Research"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "30000",
    budgetMax: "55000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 126,
    clickCount: 78,
  },
  {
    id: "e0000000-0000-0000-0000-000000000007",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "devops-cloud",
    slug: "aws-ve-kubernetes-ile-cok-bolgeli-ci-cd-dagitim-hatti-mimarisi-p7q8r9",
    status: "ACTIVE",
    title: "AWS ve Kubernetes ile Çok Bölgeli CI/CD Dağıtım Hattı Mimarisi",
    summary:
      "Terraform ile altyapı kodlama (IaC), GitHub Actions ile otomatik test/dağıtım pipeline'ı ve EKS cluster kurulumu yapılacak.",
    scope:
      "Dockerize edilmiş mikroservislerin Kubernetes (EKS) üzerinde yüksek erişilebilirlik ve otomatik ölçekleme (HPA) ile çalıştırılması, Prometheus ve Grafana ile izleme sisteminin kurulması gerekmektedir.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: false },
    tags: ["AWS", "Kubernetes", "Docker", "Terraform", "GitHub Actions"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "40000",
    budgetMax: "70000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 153,
    clickCount: 95,
  },
  {
    id: "e0000000-0000-0000-0000-000000000008",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "web-development",
    slug: "kurumsal-b2b-musteri-portali-ve-entegrasyon-gelistirilmesi-w1w2w3",
    status: "ACTIVE",
    title: "Kurumsal B2B Müşteri Portalı ve Entegrasyon Geliştirilmesi",
    summary:
      "Kurumsal müşterilerin sipariş takibi, fatura görüntüleme ve destek taleplerini yönetebileceği modern portal.",
    scope:
      "Next.js App Router, TypeScript ve Tailwind CSS ile responsive portal arayüzü kurulacak, ERP REST API'leri ile çift yönlü veri senkronizasyonu sağlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: true },
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "REST API"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "30000",
    budgetMax: "50000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 168,
    clickCount: 104,
  },
  {
    id: "e0000000-0000-0000-0000-000000000009",
    ownerUserId: "d0000000-0000-0000-0000-000000000002",
    categoryKey: "frontend-ui",
    slug: "react-ve-tailwind-ile-fintech-analitik-dashboard-arayuzu-f1f2f3",
    status: "ACTIVE",
    title: "React ve Tailwind ile Fintech Analitik Dashboard Arayüzü",
    summary:
      "Gerçek zamanlı grafikler, tablo filtreleri ve işlem akışlarını gösteren yüksek performanslı analitik paneli.",
    scope:
      "WebSocket üzerinden akan finansal verileri kasmadan render edebilecek, koyu tema destekli ve modüler bir dashboard geliştirilecektir.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: true },
    tags: ["React", "Tailwind CSS", "Chart.js", "TypeScript", "WebSocket"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "28000",
    budgetMax: "45000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 195,
    clickCount: 122,
  },
  {
    id: "e0000000-0000-0000-0000-000000000010",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "frontend-ui",
    slug: "tasarim-sistemi-icin-storybook-ve-accessible-bilesen-kutuphanesi-f4f5f6",
    status: "ACTIVE",
    title: "Tasarım Sistemi için Storybook ve Accessible Bileşen Kütüphanesi",
    summary:
      "WCAG 2.1 AA uyumlu, tema destekli ve Storybook ile belgelenmiş UI bileşen kütüphanesi kodlanacaktır.",
    scope:
      "Butonlar, form elemanları, modal ve popover bileşenleri Radix UI primitifleri üzerine inşa edilecek, npm paketi olarak derlenecektir.",
    answersJson: { authRequired: false, adminRequired: false, responsiveRequired: true },
    tags: ["React", "Storybook", "TypeScript", "Radix UI", "Tailwind CSS"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "20000",
    budgetMax: "35000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 110,
    clickCount: 65,
  },
  {
    id: "e0000000-0000-0000-0000-000000000011",
    ownerUserId: "d0000000-0000-0000-0000-000000000002",
    categoryKey: "backend-api",
    slug: "node-js-ve-redis-ile-dagitik-bildirim-ve-event-motoru-b1b2b3",
    status: "ACTIVE",
    title: "Node.js ve Redis ile Dağıtık Bildirim ve Event Motoru",
    summary:
      "Milyonlarca anlık push bildirimi ve e-posta tetiklemesini düşük gecikmeyle yöneten kuyruk ve event servisi.",
    scope:
      "BullMQ, Redis Cluster ve Node.js worker havuzu kullanılarak hata durumunda otomatik yeniden deneme (retry) ve dead-letter queue mekanizmaları kurulacaktır.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: false },
    tags: ["Node.js", "TypeScript", "Redis", "BullMQ", "PostgreSQL"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "32000",
    budgetMax: "55000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 135,
    clickCount: 88,
  },
  {
    id: "e0000000-0000-0000-0000-000000000012",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "backend-api",
    slug: "iyzico-ve-stripe-odeme-gecidi-ve-abonelik-sistemi-entegrasyonu-b4b5b6",
    status: "ACTIVE",
    title: "İyzico ve Stripe Ödeme Geçidi ve Abonelik Sistemi Entegrasyonu",
    summary:
      "Tekrarlayan ödemeler, 3D Secure, fatura oluşturma ve webhook dinleyicilerini kapsayan ödeme altyapısı.",
    scope:
      "Abonelik planları, kupon tanımlama ve iade akışları PCI-DSS uyumluluk prensiplerine uygun olarak kodlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: false },
    tags: ["Node.js", "Stripe", "İyzico", "PostgreSQL", "Webhooks"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "25000",
    budgetMax: "42000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 160,
    clickCount: 102,
  },
  {
    id: "e0000000-0000-0000-0000-000000000013",
    ownerUserId: "d0000000-0000-0000-0000-000000000002",
    categoryKey: "mobile-development",
    slug: "react-native-ile-kurye-ve-saha-teslimat-takip-uygulamasi-m1m2m3",
    status: "ACTIVE",
    title: "React Native ile Kurye ve Saha Teslimat Takip Uygulaması",
    summary:
      "Arka planda konum takibi, rota optimizasyonu ve barkod okuma özellikleri içeren hibrit mobil uygulama.",
    scope:
      "React Native & Expo ile iOS ve Android için kurye operasyon ekranları, teslimat anı dijital imza ve offline veri saklama modülü kodlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: true },
    tags: ["React Native", "TypeScript", "Expo", "Mapbox", "Redux"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "38000",
    budgetMax: "65000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 145,
    clickCount: 92,
  },
  {
    id: "e0000000-0000-0000-0000-000000000014",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "ai-ml",
    slug: "llm-ve-vision-modelleri-ile-akilli-fatura-ve-belge-ayristirma-a1a2a3",
    status: "ACTIVE",
    title: "LLM ve Vision Modelleri ile Akıllı Fatura ve Belge Ayrıştırma",
    summary:
      "Taranmış fatura ve makbuzları OCR ile okuyup muhasebe formatına dönüştüren yapay zeka otomasyonu.",
    scope:
      "GPT-4o Vision ve Tesseract pipeline'ı ile PDF/görsellerden tablo ve alan çıkarma servisi kurulacak, doğruluk oranı %98 üzerinde hedeflenecektir.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: false },
    tags: ["Python", "OCR", "OpenAI", "Tesseract", "FastAPI"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "35000",
    budgetMax: "60000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 3,
    timelineUnit: "WEEKS",
    viewCount: 175,
    clickCount: 115,
  },
  {
    id: "e0000000-0000-0000-0000-000000000015",
    ownerUserId: "d0000000-0000-0000-0000-000000000002",
    categoryKey: "web-development",
    slug: "headless-shopify-ve-nextjs-ile-ultra-hizli-marka-magazasi-w4w5w6",
    status: "ACTIVE",
    title: "Headless Shopify ve Next.js ile Ultra Hızlı Marka Mağazası",
    summary:
      "Shopify Storefront API, Algolia arama ve Next.js ISR önbellek mimarisiyle global e-ticaret vitrini.",
    scope:
      "Core Web Vitals puanı 95+ hedeflenen, çok dilli ve çok para birimli headless e-ticaret frontend'i kodlanacaktır.",
    answersJson: { authRequired: true, adminRequired: false, responsiveRequired: true },
    tags: ["Next.js", "Shopify", "Tailwind CSS", "TypeScript", "Algolia"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "40000",
    budgetMax: "75000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 4,
    timelineUnit: "WEEKS",
    viewCount: 220,
    clickCount: 140,
  },
  {
    id: "e0000000-0000-0000-0000-000000000016",
    ownerUserId: "d0000000-0000-0000-0000-000000000001",
    categoryKey: "ui-ux-design",
    slug: "mobil-saglik-ve-tele-tip-uygulamasi-icin-ux-arastirmasi-ve-tasarim-u1u2u3",
    status: "ACTIVE",
    title: "Mobil Sağlık ve Tele-Tıp Uygulaması için UX Araştırması ve Tasarım",
    summary:
      "Doktor-hasta görüntülü görüşme, tahlil geçmişi ve reçete takibini kolaylaştıran sezgisel arayüz tasarımı.",
    scope:
      "Kullanıcı testleri, empati haritaları ve tasarım prototipi hazırlanacak, Figma üzerinde eksiksiz tasarım sistemi teslim edilecektir.",
    answersJson: { authRequired: false, adminRequired: false, responsiveRequired: true },
    tags: ["Figma", "UI/UX", "User Research", "Wireframing", "Mobile Design"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "24000",
    budgetMax: "40000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 130,
    clickCount: 82,
  },
  {
    id: "e0000000-0000-0000-0000-000000000017",
    ownerUserId: "d0000000-0000-0000-0000-000000000002",
    categoryKey: "devops-cloud",
    slug: "postgresql-icin-yuksek-erisebilirlik-ve-otomatik-yedekleme-kurgusu-d1d2d3",
    status: "ACTIVE",
    title: "PostgreSQL için Yüksek Erişilebilirlik ve Otomatik Yedekleme Kurgusu",
    summary:
      "Patroni, PgBouncer ve WAL-G ile sıfır veri kaybı hedefli veritabanı replikasyon ve failover mimarisi.",
    scope:
      "Multi-AZ dağıtımda primary-standby replikasyon kurulumu, bağlantı havuzlama ve S3/GCS otomatik şifreli yedekleme konfigüre edilecektir.",
    answersJson: { authRequired: true, adminRequired: true, responsiveRequired: false },
    tags: ["PostgreSQL", "PgBouncer", "Docker", "Linux", "Backup"],
    budgetMode: "FIXED_RANGE",
    budgetCurrency: "TRY",
    budgetMin: "25000",
    budgetMax: "45000",
    timelineMode: "DURATION_ESTIMATE",
    timelineValue: 2,
    timelineUnit: "WEEKS",
    viewCount: 118,
    clickCount: 74,
  },
];
