import {
  Globe,
  Smartphone,
  Monitor,
  Server,
  Layout,
  Cpu,
  Database,
  Cloud,
  ShieldCheck,
  CheckCircle2,
  Palette,
  Workflow,
  HardDrive,
  Gamepad2,
  Network,
  Wrench,
  Radio,
  Blocks,
  Compass,
  Code2,
  TrendingUp,
  Video,
  PenTool,
  Briefcase,
  Scale,
  Box,
  Headphones,
  Bot,
  Sparkles,
  BarChart3,
  Layers,
  Share2,
  Feather,
  Package,
  Presentation,
  Megaphone,
  Mail,
  ShoppingBag,
  Film,
  Clapperboard,
  Mic,
  FileCode,
  FileText,
  FileSignature,
  Building,
  Home,
  CheckSquare,
  Coins,
  Calculator,
  Receipt,
  Glasses,
  Camera,
  Music,
  UserCheck,
  GraduationCap,
  Search,
  type LucideIcon,
} from "lucide-react";

export const SECTOR_ICONS: Record<string, LucideIcon> = {
  "sector-software-it": Code2,
  "sector-ai-data": Cpu,
  "sector-design-creative": Palette,
  "sector-marketing-growth": TrendingUp,
  "sector-video-audio": Video,
  "sector-writing-translation": PenTool,
  "sector-business-finance": Briefcase,
  "sector-legal-compliance": Scale,
  "sector-engineering-3d": Box,
  "sector-operations-support": Headphones,
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // Sektör 1: Yazılım & BT
  "web-development": Globe,
  "frontend-ui": Layout,
  "backend-api": Server,
  "mobile-development": Smartphone,
  "desktop-development": Monitor,
  "devops-cloud": Cloud,
  database: HardDrive,
  cybersecurity: ShieldCheck,
  "qa-testing": CheckCircle2,
  blockchain: Blocks,
  "embedded-iot": Radio,
  "it-systems-network": Network,
  "computer-hardware": Wrench,
  "other-technology": Code2,
  "nocode-lowcode-development": Workflow,

  // Sektör 2: AI & Veri
  "ai-ml": Cpu,
  "data-engineering": Database,
  "automation-integrations": Workflow,
  "ai-agents-workflows": Bot,
  "prompt-engineering": Sparkles,
  "business-intelligence": BarChart3,

  // Sektör 3: Tasarım
  "ui-ux-design": Palette,
  "brand-identity-logo": Feather,
  "design-systems": Layers,
  "social-media-design": Share2,
  "illustration-vector": Palette,
  "print-packaging-design": Package,
  "presentation-deck-design": Presentation,
  "photo-editing-retouching": Camera,

  // Sektör 4: Pazarlama & Büyüme
  "search-engine-optimization": TrendingUp,
  "paid-search-sem": Megaphone,
  "paid-social-meta": Share2,
  "social-media-management": Megaphone,
  "email-marketing-automation": Mail,
  "ecommerce-growth-store": ShoppingBag,

  // Sektör 5: Video & Ses
  "short-form-video": Film,
  "long-form-youtube": Video,
  "motion-graphics-2d-3d": Clapperboard,
  "voice-over-dubbing": Mic,
  "podcast-audio-editing": Mic,
  "music-production-beatmaking": Music,

  // Sektör 6: Yazı & Çeviri
  "technical-writing": FileCode,
  "copywriting-sales": FileText,
  "seo-blog-writing": PenTool,
  "translation-localization": Globe,
  "proofreading-editing": CheckSquare,

  // Sektör 7: Finans & Danışmanlık
  "technical-consulting": Compass,
  "financial-modeling": Calculator,
  "accounting-bookkeeping": Receipt,
  "tax-consulting": Coins,
  "startup-strategy-bizdev": Briefcase,
  "project-management-agile": Workflow,
  "hr-talent-recruitment": UserCheck,
  "online-tutoring-mentorship": GraduationCap,

  // Sektör 8: Hukuk & Mevzuat
  "contract-drafting-review": FileSignature,
  "kvkk-gdpr-privacy": ShieldCheck,
  "trademark-ip-patent": Scale,
  "ecommerce-consumer-law": ShoppingBag,

  // Sektör 9: Mühendislik & 3D
  "game-development": Gamepad2,
  "architectural-design-bim": Building,
  "interior-design-rendering": Home,
  "3d-product-modeling": Box,

  // Sektör 10: Operasyon & Destek
  "executive-virtual-assistant": Headphones,
  "customer-support-crm": Headphones,
  "data-entry-web-research": Search,

  // Granular Alt Kategoriler
  "fullstack-development": Code2,
  "ecommerce-development": ShoppingBag,
  "cms-nocode-development": Layout,
  "api-microservices": Server,
  "penetration-testing-security": ShieldCheck,
  "cloud-infrastructure-aws-gcp": Cloud,
  "llm-app-development": Bot,
  "computer-vision-ai": Cpu,
  "nlp-speech-voice": Mic,
  "data-scraping-extraction": HardDrive,
  "web-ui-design": Layout,
  "mobile-app-ui-ux": Smartphone,
  "icon-typography-design": PenTool,
  "character-concept-art": Palette,
  "technical-seo-audit": Search,
  "tiktok-video-ads": Film,
  "b2b-growth-linkedin": TrendingUp,
  "content-marketing-strategy": Feather,
  "video-color-grading": Clapperboard,
  "product-3d-animation": Box,
  "subtitles-transcription": FileText,
  "sound-design-sfx": Headphones,
  "software-i18n-localization": Globe,
  "academic-medical-translation": FileCode,
  "whitepaper-ebook-writing": FileText,
  "ghostwriting-thought-leadership": PenTool,
  "market-research-analysis": BarChart3,
  "pitch-deck-financials": Presentation,
  "operations-process-optimization": Workflow,
  "freelance-client-agreements": FileSignature,
  "nda-confidentiality-drafting": ShieldCheck,
  "terms-privacy-saas": FileCode,
  "unity-game-development": Gamepad2,
  "unreal-engine-development": Gamepad2,
  "mobile-casual-game-dev": Smartphone,
  "game-2d-pixel-art": Palette,
  "game-3d-assets-characters": Box,
  "game-level-mechanics-design": Compass,
  "game-audio-music": Headphones,
  "architectural-exterior-rendering": Building,
  "3d-printing-stl-modeling": Box,
  "xr-spatial-computing-vr-ar": Glasses,
  "ecommerce-store-operations": ShoppingBag,
  "lead-data-enrichment": Search,
  "transcription-audio-to-text": Mic,
};
